vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set encoding=UTF-8")
vim.cmd("set smartindent")
vim.cmd("inoremap jk <ESC>")
vim.cmd("set backspace=indent,eol,start")
vim.cmd("set number")
vim.cmd("set noswapfile")
vim.cmd("set relativenumber")
vim.cmd("set hlsearch")
vim.cmd("set ignorecase")
vim.cmd("set incsearch")
vim.cmd("set nowrap")
vim.cmd("set scrolloff=8")
vim.cmd("set cmdheight=1")
vim.cmd("set exrc")
vim.g.mapleader = " "
